### ISSUE TITLE
GMVP Optimization Bounded K Clustering

### ISSUE THREAD

**Issue by Chuongtran1312** [hellojinwoo/CA_GMVP#1]
Hi, I am trying to test this code on my stock portfolio but I got these issues
**1. Import cudf**

I could not install cudf and import it and I think that it is just available on Linux. For t-sne, instead
`import cudf
from cuml.manifold import TSNE`
could I use this code 
`from sklearn.decomposition import TSNE`
or do you have any solution?

**2. GMVP_between_clusters function** 

For this function, the line `scaled_daily_return_PCA_array = pca.fit_transform(current_daily_return_df)` is not working because  the current_daily_return_df is not identified. Is that indeed the after_scaling_return_df ?

**3. Components**

How could you determine the number of components for t-sne and PCA?

Thank you,
Ben

**Comment by hellojinwoo** [comment]
Sorry for taking it so long to reply you back.

**1. Import cudf**
It is much easier to install `sklearn` and it is more of a standard in ML community to use `sklearn`. So I actually updated my codes to use `sklearn` instead of `cudf`. Thank you for your suggestion.

**2. GMVP_between_clusters function**
It must be due to I used quotation mark ("", '') while using the `argparse`. For example it should have been `--dim_reduction_method PCA`, rather than `--dim_reduction_method 'PCA'`. The README.md file has been updated as well, so please check it out.

**3. Components**
The default values of `no_of_PCA_components` and `no_of_tsne_components` have been updated to 3, just for visualization purpose. The 3-long vectors can be easily visualized in the 3D plots. I would recommend you to experiment with the numbers. In my opinion, I do not think 252-long vectors are long, so we do not need to use dimensionality reduction methods such as PCA.
